import { StyleSheet } from 'react-native';
export default StyleSheet.create({
    mainContainer: {
        backgroundColor: 'rgb(244,244,244)',
        height: '100%',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'flex-start',
        padding: 0,
        marginTop: 0,
    },
    buttonContainer: {
        alignSelf: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        aspectRatio: 19/4,
        height: '25%',
        borderRadius: 4,
        marginBottom: 13,
        flex: 3.5/60,
        resizeMode: 'contain',
    },
    loginButton: {
        backgroundColor: '#9E1B32',
    },
    loginButtonText: {
        color: 'white',
        fontSize: 14,
        fontWeight: 'bold',
    },
    topBar: {
        width:'100%',
        height: '200%',
        flexDirection: 'row',
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: "94%",
        marginTop: "1%",
        marginBottom: "3%",
        flex: 3/20,
    },
    pbContainer: {
        alignItems: 'flex-start',
        flex: 1/8,
        width: undefined,
        height: "48%",
        justifyContent: 'center',
        resizeMode: 'contain',
        marginRight: "3%",
    },
    hamburger: {
        alignItems: 'flex-end',
        flex: 1/8,
        width: undefined,
        height: "42%",
        justifyContent: 'center',
        resizeMode: 'contain',
        marginLeft: "3%",
    },
    ualogo: {
        width: undefined,
        height: "80%",
        flex: 5/8,
        resizeMode: 'contain',
    },
    svgWrapper: {
        width: "90%",
        height: "100%",
        justifyContent: 'center',
        alignItems: 'flex-start',
        flex: 17.5/20,
        resizeMode: 'contain',
        marginBottom: "0%",
    },
    bottomButtonContainer: {
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'center',
        width: 400,
        marginBottom: "2%",
        marginTop: "5%",
        flex: 5.5/20,
    },
    bottomBar: {
        // flexDirection: 'row',
        // alignItems: 'center',
        // justifyContent: 'space-between',
        // flex: 2/20,
        width: "100%",
    }
});